#!/bin/bash
# Prepare and start X11 
# $Id$


if [ -n "$WINDOWMANAGER" ]; then
    echo "allowed_users=anybody" > /etc/X11/Xwrapper.config


    echo "exec $WINDOWMANAGER" >> /etc/X11/xinit/xinitrc
    


    if [ ! -e /home/$USERNAME/.xinitrc ]; then
	cp /etc/X11/xinit/xinitrc /home/$USERNAME/.xinitrc 2>/dev/null
    fi

fi

echo "Window manager is: $WINDOWMANAGER"
