#!/bin/sh
# 

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac
. /conf/initramfs.conf
echo "BASE=\"$BASE\"" >>  ${rootmnt}/$FILECONF
echo "KERNEL_VER=\"$KERNEL_VER\""  >>  ${rootmnt}/$FILECONF
echo "DELIVER=\"$DELIVER\""  >>  ${rootmnt}/$FILECONF
echo "TORAM=\"$TORAM\"" >> ${rootmnt}/$FILECONF
echo "QEMU=\"$QEMU\"" >> ${rootmnt}/$FILECONF
echo "LIVECD=\"$LIVECD\"" >> ${rootmnt}/$FILECONF
echo "LIVEDEV=\"$LIVECD\"" >> ${rootmnt}/$FILECONF
echo "UNIONFS=\"$UNIONFS\""
echo "FUNCS=\"$FUNCS\""  >> ${rootmnt}/$FILECONF
echo "FILECONF=\"$FILECONF\""  >> ${rootmnt}/$FILECONF
echo "USERNAME=\"$USERNAME\"" >> ${rootmnt}/$FILECONF
echo "HOSTNAME=\"$HOSTNAME\"" >> ${rootmnt}/$FILECONF
echo "LANGUAGE=\"$LANGUAGE\"" >> ${rootmnt}/$FILECONF
echo "NOSWAP=\"$NOSWAP\"" >> ${rootmnt}/$FILECONF
echo "DMA=\"$DMA\"" >> ${rootmnt}/$FILECONF
echo "MNTPOINT=\"$MNTPOINT\"" >> ${rootmnt}/$FILECONF
echo "LCONF=\"$LCONF\"" >> ${rootmnt}/$FILECONF
echo "XCONF=\"$XCONF\"" >> ${rootmnt}/$FILECONF
echo "ROOTDSS=\"$ROOTDSS\"" >> ${rootmnt}/$FILECONF
echo "RCDIR=\"$RCDIR\"" >> ${rootmnt}/$FILECONF
echo "INCLUDEME=\"$INCLUDEME\"" >> ${rootmnt}/$FILECONF

for x in $(cat /proc/cmdline); do
	case $x in	
		xconf=*)
			XCONF=${x#xconf=}
			;;
        lconf=*)
            LCONF=${x#lconf=}
            ;;
    esac
done

echo "LCONF=\"$LCONF\"" >> ${rootmnt}/$FILECONF
echo "XCONF=\"$XCONF\"" >> ${rootmnt}/$FILECONF


# XXX Ugly hack to be sure the $init is a copy in the memory and not in the mounted image
if [ -f "${rootmnt}${init}" ]; then
	mv ${rootmnt}${init} ${rootmnt}${init}_
	mv ${rootmnt}${init}_ ${rootmnt}${init}
fi		

# Arrange for shells on virtual consoles, rather than login prompts
#. /conf/initramfs.conf
#sed -i -e "s|^\([^:]*:[^:]*:[^:]*\):.*getty.*\<\(tty[0-9]*\).*$|\1:/bin/login -f $USERNAME </dev/\2 >/dev/\2 2>\&1|" ${rootmnt}/etc/inittab


# This has the nice side effect of the cron.{daily,weekly,monthly} jobs in
# /etc/crontab remaining disabled, yet also not run by anacron
for file in anacron postfix checkfs.sh checkroot.sh hdparm ntpdate mountall.sh ; do
	if [ -f "${rootmnt}/etc/init.d/${file}" ];then
		echo "deleting ${rootmnt}/etc/init.d/${file}..." >> /tmp/initramfs.debug
		: > ${rootmnt}/etc/init.d/${file}
	fi
done

exit 0
