#!/bin/sh
# 
# default:
# lang=$LANG (from iniramfs.conf)
#
# cmds:
#  loadkeys -q $KEYTABLE &
#  consolechars -f $CONSOLEFONT &

# cheatcodes:
# lang=<var> [change defualt lang]
# KDE config
# keyboard=<var>  [override text keyboard]
# xkeyboard=<var> [override x keyboard]
# tz=<var>        [override zoneinfo ]
# langconf=[noninteractive|dialog] [frontend to use to reconfigure locales]

# dpkg-reconfigure libc6
# /usr/share/zoneinfo/localtime -> /etc/localtime
# /etc/localtime -> /usr/share/zoneinfo/Europe/Rome [ex: tz=Europe/Rome]

# files:
# /etc/environment
# /etc/locale.gen
PREREQ="fstab"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. /conf/initramfs.conf
. ${rootmnt}/$FUNCS
. ${rootmnt}/$FILECONF

language="$(getbootparam lang)"
if [ -n "${language}" ];then
	LANGUAGE=${language}	
fi
setlocales
echo "LANG=\"$LANG\""                 >> ${rootmnt}/$FILECONF
echo "COUNTRY=\"$COUNTRY\""           >> ${rootmnt}/$FILECONF
echo "LANGUAGE=\"$LANGUAGE\""         >> ${rootmnt}/$FILECONF
echo "CHARSET=\"$CHARSET\""           >> ${rootmnt}/$FILECONF
echo "KEYTABLE=\"$KEYTABLE\""         >> ${rootmnt}/$FILECONF
echo "XKEYBOARD=\"$XKEYBOARD\""       >> ${rootmnt}/$FILECONF
echo "KDEKEYBOARD=\"$KDEKEYBOARD\""   >> ${rootmnt}/$FILECONF
echo "KDEKEYBOARDS=\"$KDEKEYBOARDS\"" >> ${rootmnt}/$FILECONF
echo "CONSOLEFONT=\"$CONSOLEFONT\""   >> ${rootmnt}/$FILECONF
echo "DESKTOP=\"$DESKTOP\""           >> ${rootmnt}/$FILECONF
echo "TZ=\"$TZ\""                     >> ${rootmnt}/$FILECONF

keyboard="$(getbootparam keyboard 2>/dev/null)"
if [ -n "${keyboard}" ];then
	echo "KEYTABLE=\"${keyboard}\"" >> ${rootmnt}/$FILECONF
fi 
xkeyboard="$(getbootparam xkeyboard 2>/dev/null)"
if [ -n "${xkeyboard}" ]; then
	echo "XKEYBOARD=\"${xkeyboard}\""  >> ${rootmnt}/$FILECONF
	echo "KDEKEYBOARD=\"${xkeyboard}\"" >> ${rootmnt}/$FILECONF
fi
tz="$(getbootparam tz 2>/dev/null)"
if [ -n "${tz}" ];then
	KTZ=${tz}
	echo "KTZ=\"${tz}\""               >> ${rootmnt}/$FILECONF  
        if [ -f "${rootmnt}/usr/share/zoneinfo/{$tz}" ];then 
		TZ=${tz}
		echo "TZ=\"$KTZ\"" >> ${rootmnt}/$FILECONF
	fi
fi
if [ -f "${rootmnt}/usr/share/zoneinfo/$TZ" ];then
cp " ${rootmnt}/usr/share/zoneinfo/$TZ"  ${rootmnt}/etc/localtime
fi

langconf=$(getbootparam langconf 2>/dev/null)
if [ "${langconf}" = "dialog" ];then
	LCONF=${langconf}
fi

# used by dpkg-reconfigure -f$nagfrontend locales
echo "LCONF=\"$LCONF\"" >> ${rootmnt}/$FILECONF
echo LANG="$LANG" > ${rootmnt}/etc/environment
echo "$LANG  $CHARSET" > ${rootmnt}/etc/locale.gen



exit 0
