#!/bin/sh
set -x
# $Id$
EDEVELOP=nomed@edevelop.org:/home/nomed/public_html/preA
md5sum dup.sh > dup.md5sum
scp  dup.sh $EDEVELOP
scp  dup.md5sum $EDEVELOP
scp COPYING $EDEVELOP
scp README $EDEVELOP
svn commit
