#!/bin/bash
# Prepare and start X11 
# $Id$

# use $dpi from cmdline ?

if [ -e "/usr/bin/X11/startx" ];then
echo "starting x11"
if [ -n "$WINDOWMANAGER" ]; then
     su -c "/usr/bin/X11/startx -- -dpi 94 " - $USERNAME & 
fi
else
	echo Login as $USERNAME	
fi

