#!/bin/sh -e

# $Progeny: init 4087 2004-02-13 01:36:47Z imurdock $

test -x /sbin/discover-modprobe || exit 0

. /etc/default/rcS
[ -e /lib/lsb/init-functions ] && logbegin="log_begin_msg  "Discovering hardware...""  && logend="log_end_msg 0" && . /lib/lsb/init-functions 

case "$1" in
start|restart)
    $logbegin
    discover-modprobe -v 2>&1 >/dev/null
	$logend
    ;;
stop|reload|force-reload)
    ;;
esac
		
