#!/bin/sh

# $Id$

# DSS-LV 
# Daniele Favara <danjele@gmail.com> 2005
# <http://dss.berlios.de>


# cmdline: xconf=dialog|noninteractive(default)

set -e
VERBOSE=yes
TMPTIME=0
[ -f /etc/default/rcS ] && . /etc/default/rcS
. /lib/lsb/init-functions
. /etc/deliver.conf
. $FUNCS




[ ! -e /etc/X11/xorg.conf ] && :>/etc/X11/xorg.conf


log_begin_msg "Generating xorg.conf..."
#DEBIAN_FRONTEND=$xfrontend dpkg-reconfigure xserver-xorg 2>/dev/null
dpkg-reconfigure -f$xfrontend  xserver-xorg 2>/dev/null

if [ "$xfrontend" = "noninteractive" ]
then
# to print > $2:
# 1) cut -d' ' -f2-
# 2) sed 's|^[^ ]* ||' 
	LANGOLD=$(grep '"XkbLayout"' /etc/X11/xorg.conf | awk '{print $3}')
	LANGCLEAN=${LANGOLD//'"'}
	if [ -n "$XKEYBOARD" ] ; then
		sed -i "s/\"$LANGCLEAN\"$/\"$XKEYBOARD\"/" /etc/X11/xorg.conf
	else
		sed -i "s/\"$LANGCLEAN\"$/\"us\"/" /etc/X11/xorg.conf
	fi
	
fi
log_end_msg $?

exit 0

