#!/bin/sh
# Try to find and load a drm module for this graphics card
# ripped from Knopper's xsession
# $Id: drm,v 1.2 2004/10/18 01:32:56 alextreme Exp $
#if [ -f /morphix/include.sh ] ; then
#	includeme=/morphix/include.sh
#elif [ -f /DSSLV/include.sh ] ; then
#	includeme=/DSSLV/include.sh
#fi
#. $includeme >/dev/null 2>&1

if [ -n "$XMODULE" ]; then
  for i in /lib/modules/`uname -r`/kernel/drivers/char/drm/*; do
    case "$i" in *$XMODULE*) modprobe $XMODULE;; esac
  done
fi

