#!/bin/sh
# wait until X is locked
# $Id$


if [ -e "/usr/bin/X11/startx" ];then

if [ -n "$WINDOWMANAGER" ]; then
    for i in 1 2 3 4 5 6 7 8 9 10
      do
      if [ -f /tmp/.X0-lock ]; then
	  break
	  sleep 1
      fi
    done
fi
fi
exit 0
