#!/bin/sh
# Set sudo if it is installed and not already configured for current user
# Also make sure the default permissions are correct (0440)
# $Id: sudoers,v 1.4 2005/03/24 00:34:32 alextreme Exp $

if [ -e /etc/sudoers ]; then
  if ! grep -q $USER /etc/sudoers
  then
    echo -e "$USER ALL=NOPASSWD: ALL \n" >> /etc/sudoers
  fi
  chmod 0440 /etc/sudoers
fi

