#!/bin/sh
exec 1>&2
echo -n "Launching esetroot... "
if ps -C esetroot -o user | grep -q $USER
then
  echo "Already running."
  exit
else
  echo "OK"
  exec esetroot -scale $HOME/desktop-background.png &
fi
