#!/bin/bash
#sh /usr/share/xtdesktop/autostart.sh &
sudo banana start &
#xloadimage  -onroot -fullscreen -center -border black /etc/alternatives/desktop-background &
xtdesk &
esetroot -scale /etc/alternatives/desktop-background &
ivman &

