#!/bin/bash

start_xtdesk () {
source /lib/lsb/DSSLV-functions
source $HOME/.ivman/default
[ -e /tmp/.lasticon ] && rm -f  /tmp/.lasticon
rm -f $HOME/.xtdesktop/allow*.lnk
x=300
y=300
num=1
entry=$(get_partitions)
cdrom="/dev/$(get_cdroms)"
entry="$entry $cdrom"
echo $entry

# if removable in ivicons
a=$(hal-find-by-capability --capability volume)
for i in $a; do
	dev=$(hal-get-property --udi $i --key block.device)
	name=$(hal-get-property --udi $i --key volume.uuid)
	echo $dev $name
	if [ -n "$dev" ];then
		if [ -n "$name" ];then
			entry=${entry/$dev}
			sh $HOME/.ivman/ivmanxticons -g $dev $name
		fi
	fi
done


hdicon=$HOME/.xtdesktop/hd.png
cdromicon=$HOME/.xtdesktop/cdrom_mount.png
for i in $entry; do
	set -x
	mpoint=`$MOUNTPOINT $i`
	
	lnk=$(basename $i)
	if [ -z "$mpoint" ];then
	 mpoint=/media/$lnk
	fi
	ICONTYPE=$(echo $cdrom | grep $i)
	if [ -n "$ICONTYPE" ];then
		ICON=$cdromicon
	else
		ICON=$hdicon
	fi
	
	if [ ! -e "$HOME/.xtdesktop/$lnk.lnk" ];then
	echo "table Icon" >> $HOME/.xtdesktop/allow$lnk.lnk
	echo "Type: Program" >> $HOME/.xtdesktop/allow$lnk.lnk
	echo "Caption: $lnk" >> $HOME/.xtdesktop/allow$lnk.lnk
	echo "Command: $FM $mpoint" >> $HOME/.xtdesktop/allow$lnk.lnk
	echo "Icon: $ICON" >> $HOME/.xtdesktop/allow$lnk.lnk
	echo "X: $x" >> $HOME/.xtdesktop/allow$lnk.lnk
	echo "Y: $y" >> $HOME/.xtdesktop/allow$lnk.lnk
	echo "MenuCommand1: Mount $mpoint : notify.py -p $i -s 'Device Mounted' -m \"mount point $mpoint\" ">> $HOME/.xtdesktop/allow$lnk.lnk
	echo "MenuCommand2: Umount $mpoint : notify.py -u $i -s 'Device Unmounted' -m  \"device name $i\"  ">> $HOME/.xtdesktop/allow$lnk.lnk 
	echo "end" >> $HOME/.xtdesktop/allow$lnk.lnk
	let x+=80 
	if [ "$num" = "6" ];then
	let y+=90
	num=0
	fi
	let num+=1
	echo $x $y $num> /tmp/.lasticon
	fi
set +x
done
}

exec 1>&2
echo -n "Launching xtdesktop... "
if ps -C xtdesk -o user | grep -q $USER
then
  echo "Already running."
  exit
else
  echo "OK"
  start_xtdesk
  exec xtdesk &
fi 


if ps -C ivicons -o user | grep -q $USER
then
  echo "Already running."
  exit
else
  echo "OK"
  exec ivicons &
fi 



