#!/bin/sh
# $Id$

# Set up the /etc/network/interfaces file depending on the
# current state of the network devices. Work in progress.
# 
# used in DSSLV-start
#
# Please note: this wipes out any old configuration

INTF="/etc/network/interfaces"

# add header

echo "# /etc/network/interfaces -- configuration file for ifup(8), ifdown(8)" > $INTF
echo >> $INTF
# Set up the loopback interface

echo "auto lo" >> $INTF
echo "iface lo inet loopback" >> $INTF

# More to come, after I figure out an easier way to parse ifconfig / proc/net output without going nuts
