#!/bin/bash
# $Id: make-iso 47 2005-10-12 17:31:04Z nomed $
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

# Daniele Favara <danjele@gmail.com> <http://dss.berlios.de>
SRC="$1"
DEST="$2"

if [ -z "$SRC" -o -z "$DEST" ]; then
    echo "Usage: $0 sourcedirectory destination.iso"
    echo
    echo "This script generates internal md5sum's for the sourcedirectory,"
    echo "and then generates a bootable live CD from the directory"
    echo "Naturally, destination.iso is the output"
    exit
fi

find $SRC/ -type f -print0 | xargs -0 md5sum > $SRC/md5sums
#if [ -e "$SRC/base/boot.img" ]; then
#    mkisofs -pad -l -r -J -v -V "DSS Live" -b base/boot.img -c base/boot.cat -hide -rr -moved -o $DEST $SRC
#elif [ -e "$SRC/boot/grub/iso9660_stage1_5" ]; then
#    mkisofs -pad -l -r -J -v -V "DSS Live" -b boot/grub/iso9660_stage1_5 -c base/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -hide -rr -moved -o $DEST $SRC
#elif [ -e "$SRC/boot/loader/isolinux.bin" ]; then
#    mkisofs -pad -l -r -J -v -V "DSS Live" -b boot/loader/isolinux.bin -c base/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -hide -rr -moved -o $DEST $SRC
if [ -e "$SRC/isolinux/isolinux.bin" ];then
	 mkisofs -v -V "dsslive" -r -J -l -L -P "DSS Live" \
     -b "isolinux/isolinux.bin" \
     -c "isolinux/boot.cat" \
     -no-emul-boot -boot-load-size 4 -boot-info-table \
     -graft-points -o $DEST \
     $SRC
else
    echo "Error: unable to find bootloader in $SRC. Either update this script, or make sure you have the right directory as src"
fi


