obj-$(CONFIG_UNION_FS) += unionfs.o

unionfs-y := subr.o dentry.o locks.o file.o inode.o main.o super.o \
	stale_inode.o branchman.o xattr.o rdstate.o copyup.o  \
	dirhelper.o rename.o unlink.o lookup.o persistent_inode.o \
	commonfops.o dirfops.o print.o
