#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Hooks for loading modules needed by yuch

. /usr/share/initramfs-tools/hook-functions

for x in unionfs squashfs loop; do
	manual_add_modules ${x}
done
