#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac
for x in $(cat /proc/cmdline); do
	case $x in
	noacpi)
		ACPI=false;
		;;
	esac
done
if [ "$ACPI" != "false" ];then
modprobe -q fan
modprobe -q thermal
fi
